### ISSUE TITLE
View created with MergeAdapter is smaller then the screen

### ISSUE THREAD

**Issue by moritzm** [commonsguy/cwac-merge#20]
I create a view with MergeAdapter containing some other single views. for example a header view, a list view etc.
My problem is, if the list is empty, i do not merge it to the adapter, but then, the created MergeAdapter view is smaller then my screen and i have an ugly "grey" are on the bottom on the screen.

Is there a way do add a background to the adapter itself? Or do you have any hints how i can "spread" my view to fill the complete screen?

![screenshot_2015-08-20-13-51-15](https://cloud.githubusercontent.com/assets/1443730/9382673/2ae4c410-4743-11e5-86e1-298d0a6cd4b4.png)

**Comment by commonsguy** [comment]
Please read the documentation, particularly [the section on where to ask questions](https://github.com/commonsguy/cwac-merge#questions).

> Is there a way do add a background to the adapter itself?

No adapters in Android have backgrounds. Adapters are not views. Your `ListView` that you might be applying the adapter to would have a background.

> Or do you have any hints how i can "spread" my view to fill the complete screen?

No, sorry.

**Comment by moritzm** [comment]
Thank you. Did not see this section. Will go to the stackoverflow section.
