### ISSUE TITLE
MergeAdapter addView Issue -> android.widget.FrameLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams

### ISSUE THREAD

**Issue by denite** [commonsguy/cwac-merge#21]
I'm getting an error on my tablet running Android Kitkat 4.4.2... (Runs perfectly on my Lollipop phone).

Seems like the my layout heading is being cast incorrectly... When I remove the header, it runs perfectly.

Here is how I am creating my header...

```
        albumHeaderView = inflater.inflate(R.layout.search_album_header, container, false);
```

And here is how I'm adding it to the adapter.

```
        mergeAdapter = new MergeAdapter();
        mergeAdapter.addView(artistHeaderView);
```

This is the error:

11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41709c08)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err: java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.ListView.setupChild(ListView.java:1839)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.ListView.makeAndAddView(ListView.java:1806)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.ListView.fillDown(ListView.java:697)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.ListView.fillFromTop(ListView.java:763)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.ListView.layoutChildren(ListView.java:1641)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.AbsListView.onLayout(AbsListView.java:2528)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.View.layout(View.java:15655)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4856)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.View.layout(View.java:15655)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4856)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.View.layout(View.java:15655)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4856)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.View.layout(View.java:15655)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4856)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
11-10 16:56:26.352 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.View.layout(View.java:15655)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4856)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:907)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.View.layout(View.java:15655)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4856)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.View.layout(View.java:15655)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4856)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.View.layout(View.java:15655)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4856)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.View.layout(View.java:15655)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4856)
11-10 16:56:26.357 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.View.layout(View.java:15655)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4856)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.View.layout(View.java:15655)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:4856)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2287)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2007)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1231)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6459)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:803)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:603)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:573)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:789)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.os.Looper.loop(Looper.java:157)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5350)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
11-10 16:56:26.362 1644-1644/com.denite.shuffleemup W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by commonsguy** [comment]
Replace:

    inflater.inflate(R.layout.search_album_header, container, false);

with:

    inflater.inflate(R.layout.search_album_header, null);

because *you* are not adding it to a container; `MergeAdapter` is.

Also, in the future, please follow [the instructions on the project's README for how to get support](https://github.com/commonsguy/cwac-merge#questions).

**Comment by denite** [comment]
Thanx
