### ISSUE TITLE
Garbage collected views

### ISSUE THREAD

**Issue by mblcdr** [commonsguy/cwac-merge#23]
I am using ```MergeAdapter``` in ```Fragment```s which are used in a ```ViewPager```. Sometimes when I am switching between pages I see that the view which is present in ```SackOfViewsAdapter``` and is not active becomes null, which results in empty layouts. The fragments which are present in ViewPager doesn't get destroyed completely though, because the ```onCreate()``` method of the fragment is not getting called. It's of worth to mention that the fragments are not retained and I tested both with ```FragmentPagerAdapter``` and ```FragmentStatePagerAdapter```.

I solved this issue by rewriting ```SackOfViewsAdapter``` and adding a method to replace views. Then when I am setting the adapter active again, I check if the view is nulled, to replace if necessary.

I suppose it's handy to have a functionality like this baked into the library.

**Comment by commonsguy** [comment]
> I see that the view which is present in SackOfViewsAdapter and is not active becomes null

An object (e.g., "the view") in Java cannot "becomes null", so I do not know what you mean by this.

**Comment by mblcdr** [comment]
I use ```addView()``` of ```MergeAdapter```. When I switch to another tab then return, in debug mode I see that the ```SackOfViewsAdapter``` is still there but when I click on it (in variables sections of android studio) it shows that all elements are null.

**Comment by commonsguy** [comment]
> it shows that all elements are null

I do not know what "elements" refers to.

If you are referring to `views`, `views` itself can only be `null` if you use the `SackOfViewsAdapter(List<View> views)` and pass in `null`. In the context of `MergeAdapter`, this would occur if you call `addViews()` with a `null` list of views, for example.

If you are referring to the contents of `views`, the only way that items within that `List<View>` can be `null` is if you make them `null` in your code, and I fail to see where `MergeAdapter` is doing this.

If you can publish the source to a project that reproduces your bug, I will take a look at it.

**Comment by mblcdr** [comment]
I'll close this for now, and reopen when I have a sample with this issue ready. Thanks.
