### ISSUE TITLE
Click event from inside a view added to the MergeAdapter

### ISSUE THREAD

**Issue by romainpiel** [commonsguy/cwac-merge#6]
Hey, first thanks a lot with your library it's really helpful.
I'm currently having an issue. I'm not sure if it's a bug related to cwac-merge but it could be. 

I've got a view with clickable widgets in it. I'm adding this view to my MergeAdapter and sometimes onClick events don't get fired until I scroll my ListView. If I click multiple times on a button, these events will get fired as many times after the scroll.

I'm not posting any code, it's as simple as it's described. I'm just adding this view to my mergeadapter and setting onclicklistener from my custom view class. I also have onItemClick listeners but I removed them and the bug was reproductible.

Have you ever been in this situation?

Thanks

**Comment by loeschg** [comment]
@RomainPiel did you find a solution to this problem?
